export const coaches = [
  {
    name: "Faker",
    game: "League of Legends",
    rate: "$350/hr",
    image: "img/faker.png",
    rating: "5 stars",
    languages: ["Korean", "English"],
  },
  {
    name: "Tenz",
    game: "Valorant",
    rate: "$150/hr",
    image: "img/tenz.png",
    rating: "4.8 stars",
    languages: ["English"],
  },
  {
    name: "K3Soju",
    game: "Teamfight Tactics",
    rate: "$80/hr",
    image: "img/k3soju.png",
    rating: "4 stars",
    languages: ["English"],
  },
  {
    name: "Puppey",
    game: "Dota 2",
    rate: "$300/hr",
    image: "img/puppey.png",
    rating: "4.5 stars",
    languages: ["Russian", "English"],
  },
  {
    name: "Coldzera",
    game: "Counter-Strike: Global Offensive",
    rate: "$200/hr",
    image: "img/coldzera.png",
    rating: "4.7 stars",
    languages: ["Portuguese", "English"],
  },
  {
    name: "Armada",
    game: "Super Smash Bros. Melee",
    rate: "$250/hr",
    image: "img/armada.jpg",
    rating: "4.5 stars",
    languages: ["Swedish", "English"],
  },
  {
    name: "Scump",
    game: "Call of Duty",
    rate: "$220/hr",
    image: "img/scump.png",
    rating: "4.5 stars",
    languages: ["English"],
  },
  {
    name: "Forest",
    game: "Counter-Strike: Global Offensive",
    rate: "$190/hr",
    image: "img/forest.jpg",
    rating: "4.6 stars",
    languages: ["Swedish", "English"],
  },
  {
    name: "Huni",
    game: "League of Legends",
    rate: "$280/hr",
    image: "img/huni.png",
    rating: "4.5 stars",
    languages: ["Korean", "English"],
  },
];
